### ISSUE TITLE
Unable to download samples.game-lobby due to the absence of Packages.json file

### ISSUE THREAD

**Issue by ahdutton** [Unity-Technologies/com.unity.services.samples.game-lobby#30]
What am I doing wrong. Trying to download this module using the GitHub link 'https://github.com/Unity-Technologies/com.unity.services.samples.game-lobby.git' pasted into the Unity Packages Manager does not work because there is no Packages.json file.  I also found this file missing from DapperDino's Lobby module download. 
Is the file hidden somehow or am I lacking a permission or something?

Andrew Dutton

**Comment by UnityJacob** [comment]
Game Lobby does not have a packages.json file as its not built as a package. We didn't design it as a package on purpose in order to allow the content to be editable and open source. 

We are currently looking to publish this on the asset store and following that package management system, which allows for easier updates while allowing the code to stay open source.

I hope that this answers your question, and if there is any feature you wish we had that packages enable, please let us know!
